---

- name: restart ssh
  service: name=ssh state=restarted
  become: yes

- name: restart mariadb
  service: name=mysql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted
  become: yes

- name: restart php
  service: name=php5-fpm state=restarted
  become: yes

- name: restart postfix
  service: name=postfix state=restarted
  become: yes

- name: restart opendkim
  service: name=opendkim state=restarted
  become: yes
