---
# Install, Secure, & Configure MariaDB

- name: Ensure MariaDB and it's Supporting Modules are Installed
  apt: name="{{ item }}"
  with_items: ['mariadb-server', 'python-mysqldb']
  become: yes

- name: Ensure the MariaDB root User has a Password Set
  mysql_user: user=root password="{{ vaulted_mysql_root_password }}" host="localhost"
  ignore_errors: yes
  become: yes

- name: Ensure the MariaDB root User is Correctly Configured
  mysql_user: user=root password="{{ vaulted_mysql_root_password }}" host="{{ item }}"
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"

- name: Ensure the Anonymous MariaDB Users are Removed
  mysql_user: user="" host="{{ item }}" state="absent"
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
  with_items: ['{{ ansible_fqdn }}', 'localhost']

- name: Ensure Remote root Access for MariaDB is Disabled
  mysql_user: user="root" host="{{ ansible_fqdn }}" state=absent
              login_user=root login_password="{{ vaulted_mysql_root_password }}"

- name: Ensure the MariaDB test Database is Removed
  mysql_db: db=test state=absent
            login_user=root login_password="{{ vaulted_mysql_root_password }}"

- name: Ensure MariaDB is Configured for Security
  ini_file: dest=/etc/mysql/my.cnf backup=yes section="mysqld"
            option="{{ item.option }}" value="{{ item.value }}"
  with_items:
    - { option: local-infile, value: 0 }
    - { option: bind-address, value: 127.0.0.1 }
  notify: restart mariadb
  become: yes

- name: Ensure the Sendy MariaDB Database Exists
  mysql_db: db=sendy
            login_user=root login_password="{{ vaulted_mysql_root_password }}"

- name: Ensure the Sendy MariaDB User is Correctly Configured
  mysql_user: user=sendy password="{{ vaulted_mysql_sendy_password }}"
              priv="sendy.*:ALL" append_privs=yes host=localhost
              login_user=root login_password="{{ vaulted_mysql_root_password }}"
